version: "3.9"

services:
  payment-initiation:
    build:
      context: .
      dockerfile: Dockerfile
    image: payment-initiation:1.0.0
    container_name: payment-initiation
    ports:
      - "8080:8080"
    environment:
      # Perfil de Spring (ajústalo según necesites)
      SPRING_PROFILES_ACTIVE: "default"
      # JVM options (puedes anular las del Dockerfile si deseas)
      JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    healthcheck:
      # Si tienes actuator
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
